{
 "title": "06 - SMB Report",
 "description": "High Level Summary of Performance Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DNS_TARGET1",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=1)"
   },
   {
    "name": "DNS_TARGET2",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=2)"
   },
   {
    "name": "DNS_TARGET3",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=3)"
   },
   {
    "name": "DNS_TARGET4",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=4)"
   },
   {
    "name": "DNS_TARGET5",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=5)"
   },
   {
    "name": "HTTP_TARGET1",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)"
   },
   {
    "name": "HTTP_TARGET2",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=2)"
   },
   {
    "name": "HTTP_TARGET3",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=3)"
   },
   {
    "name": "HTTP_TARGET4",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=4)"
   },
   {
    "name": "HTTP_TARGET5",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=5)"
   },
   {
    "name": "PING_TARGET1",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 1) "
   },
   {
    "name": "PING_TARGET2",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 2) "
   },
   {
    "name": "PING_TARGET3",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 3) "
   },
   {
    "name": "PING_TARGET4",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 4) "
   },
   {
    "name": "PING_TARGET5",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 5) "
   },
   {
    "name": "WLANPi",
    "label": "Select Probe:",
    "query": "select  \"host\", \"network\" from \"wiperf-poll-status\" where time >= now() - 14d"
   },
   {
    "name": "SMB_TARGET",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) "
   },
   {
    "name": "SMB_FILENAME1",
    "query": "SELECT \"filename\" FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_index\"=1)"
   },
   {
    "name": "SMB_FILENAME2",
    "query": "SELECT \"filename\" FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_index\"=2)"
   },
   {
    "name": "SMB_FILENAME3",
    "query": "SELECT \"filename\" FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_index\"=3)"
   },
   {
    "name": "SMB_FILENAME4",
    "query": "SELECT \"filename\" FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_index\"=4)"
   },
   {
    "name": "SMB_FILENAME5",
    "query": "SELECT \"filename\" FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_index\"=5)"
   },
   {
    "name": "SMB_TARGET1",
    "query": "SELECT \"smb_host\" FROM \"wiperf-smb\" WHERE (\"host\" =~ /$WLANPi/ AND \"smb_index\"=1)"
   },
   {
    "name": "SMB_TARGET2",
    "query": "SELECT \"smb_host\" FROM \"wiperf-smb\" WHERE (\"host\" =~ /$WLANPi/ AND \"smb_index\"=2)"
   },
   {
    "name": "SMB_TARGET3",
    "query": "SELECT \"smb_host\" FROM \"wiperf-smb\" WHERE (\"host\" =~ /$WLANPi/ AND \"smb_index\"=3)"
   },
   {
    "name": "SMB_TARGET4",
    "query": "SELECT \"smb_host\" FROM \"wiperf-smb\" WHERE (\"host\" =~ /$WLANPi/ AND \"smb_index\"=4)"
   },
   {
    "name": "SMB_TARGET5",
    "query": "SELECT \"smb_host\" FROM \"wiperf-smb\" WHERE (\"host\" =~ /$WLANPi/ AND \"smb_index\"=5)"
   }
  ]
 },
 "panels": [
  { "title": "SMB Performance Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "SMB_TARGET" },
  {
   "title": "SMB Transfer Rate - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Mbits", "label": "Avg rate" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "smb_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         " ${SMB_TARGET1} / ${SMB_FILENAME1}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET1$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT distinct(\"smb_rate\") AS \"${SMB_TARGET}  ${SMB_FILENAME2}  \" FROM \"wiperf-smb\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_host\" =~ /^$SMB_TARGET$/ AND \"filename\" =~ /^$SMB_FILENAME2$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "smb_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET2} / ${SMB_FILENAME2}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET2$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT distinct(\"smb_rate\") AS \"${SMB_TARGET}  ${SMB_FILENAME3}  \" FROM \"wiperf-smb\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_host\" =~ /^$SMB_TARGET$/ AND \"filename\" =~ /^$SMB_FILENAME3$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "smb_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET3} / ${SMB_FILENAME3}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET3$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "smb_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET4} / ${SMB_FILENAME4}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET4$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT \"lookup_time_ms\" AS \"${HTTP_TARGET1}\" FROM \"wiperf-http\" WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)",
     "select": [
      [
       { "params": [ "smb_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET5} / ${SMB_FILENAME5}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET5$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME5$/" }
     ]
    }
   ]
  },
  {
   "title": "SMB Transfer TIme - $WLANPi ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Transfer Time (s)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT distinct(\"smb_time\") AS \" ${SMB_TARGET}  ${SMB_FILENAME1}  \" FROM \"wiperf-smb\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_host\" =~ /^$SMB_TARGET$/ AND \"filename\" =~ /^$SMB_FILENAME1$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "smb_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         " ${SMB_TARGET1} / ${SMB_FILENAME1}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET1$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME1$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT distinct(\"smb_time\") AS \"${SMB_TARGET} /${SMB_FILENAME2}  \" FROM \"wiperf-smb\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_host\" =~ /^$SMB_TARGET$/ AND \"filename\" =~ /^$SMB_FILENAME2$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "smb_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET2} / ${SMB_FILENAME2}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET2$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME2$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT distinct(\"smb_time\") AS \"${SMB_TARGET} /${SMB_FILENAME3}  \" FROM \"wiperf-smb\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_host\" =~ /^$SMB_TARGET$/ AND \"filename\" =~ /^$SMB_FILENAME3$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "smb_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET3} / ${SMB_FILENAME3}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET3$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME3$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT distinct(\"smb_time\") AS \"${SMB_TARGET} /${SMB_FILENAME4}  \" FROM \"wiperf-smb\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_host\" =~ /^$SMB_TARGET$/ AND \"filename\" =~ /^$SMB_FILENAME4$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "smb_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET4} / ${SMB_FILENAME4}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET4$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME4$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-smb",
     "query": "SELECT distinct(\"smb_time\") AS \"${SMB_TARGET} /${SMB_FILENAME5}  \" FROM \"wiperf-smb\" WHERE (\"host\" =~ /^$WLANPi$/ AND \"smb_host\" =~ /^$SMB_TARGET$/ AND \"filename\" =~ /^$SMB_FILENAME5$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "smb_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "${SMB_TARGET5} / ${SMB_FILENAME5}  "
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" },
      { "condition": "AND", "key": "smb_host", "operator": "=~", "value": "/^$SMB_TARGET5$/" },
      { "condition": "AND", "key": "filename", "operator": "=~", "value": "/^$SMB_FILENAME5$/" }
     ]
    }
   ]
  },
  { "title": "Network Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Layer 2 TX Retries - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "L2 Retry Count" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "wiperf-network",
     "query": "SELECT difference(last(\"tx_retries\")) AS \"TX Retry Count\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX Retry Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Rates/Signal - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Phy Rate (Mbps)" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx PHY Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Signal Level (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel -  $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Channel" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "query": "SELECT last(\"channel\") AS \"Channel\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Channel" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless MCS (if supported by NIC) - $WLANPi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "MCS" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "tx_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx MCS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wiperf-network",
     "select": [
      [
       { "params": [ "rx_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx MCS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Details - $WLANPi",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "wiperf-network",
     "query": "SELECT \"bssid\" AS \"BSSID\", \"ssid\" AS \"SSID\", \"channel\" AS \"Channel\", \"channel_width\" AS \"Channel Width\", \"tx_rate_mbps\" AS \"Tx Phy Rate (Mbps)\", \"rx_rate_mbps\" AS \"Rx Phy Rate (Mbps)\", \"signal_level_dbm\" AS \"RSSI (dBm)\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bssid" ], "type": "field" },
       { "params": [ "BSSID" ], "type": "alias" }
      ],
      [
       { "params": [ "ssid" ], "type": "field" },
       { "params": [ "SSID" ], "type": "alias" }
      ],
      [
       { "params": [ "channel" ], "type": "field" },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "channel_width" ], "type": "field" },
       { "params": [ "Width (MHz)" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       { "params": [ "Tx Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       { "params": [ "Rx Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       { "params": [ "RSSI (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  }
 ]
}