{
 "title": "08 - Probe Health",
 "description": "High Level Summary of Performance Data",
 "tags": [ "wlanpi" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "DNS_TARGET1",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=1)"
   },
   {
    "name": "DNS_TARGET2",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=2)"
   },
   {
    "name": "DNS_TARGET3",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=3)"
   },
   {
    "name": "DNS_TARGET4",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=4)"
   },
   {
    "name": "DNS_TARGET5",
    "query": "SELECT last(\"dns_target\") FROM \"wiperf-dns\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"dns_index\"=5)"
   },
   {
    "name": "HTTP_TARGET1",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=1)"
   },
   {
    "name": "HTTP_TARGET2",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=2)"
   },
   {
    "name": "HTTP_TARGET3",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=3)"
   },
   {
    "name": "HTTP_TARGET4",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=4)"
   },
   {
    "name": "HTTP_TARGET5",
    "query": "SELECT last(\"http_target\") FROM \"wiperf-http\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"http_index\"=5)"
   },
   {
    "name": "PING_TARGET1",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 1) "
   },
   {
    "name": "PING_TARGET2",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 2)"
   },
   {
    "name": "PING_TARGET3",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 3) "
   },
   {
    "name": "PING_TARGET4",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 4) "
   },
   {
    "name": "PING_TARGET5",
    "query": "SELECT last(\"ping_host\") FROM \"wiperf-ping\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"ping_index\" = 5) "
   },
   {
    "name": "WLANPi",
    "label": "Select Probe:",
    "query": "select  \"host\", \"network\" from \"wiperf-poll-status\" where time >= now() - 14d"
   },
   {
    "name": "SMB_TARGET1",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=1)"
   },
   {
    "name": "SMB_TARGET2",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=2)"
   },
   {
    "name": "SMB_TARGET3",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=3)"
   },
   {
    "name": "SMB_TARGET4",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=4)"
   },
   {
    "name": "SMB_TARGET5",
    "query": "SELECT last(\"smb_host\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=5)"
   },
   {
    "name": "SMB_FILENAME1",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=1)"
   },
   {
    "name": "SMB_FILENAME2",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=2)"
   },
   {
    "name": "SMB_FILENAME3",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=3)"
   },
   {
    "name": "SMB_FILENAME4",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=4)"
   },
   {
    "name": "SMB_FILENAME5",
    "query": "SELECT last(\"filename\") FROM \"wiperf-smb\"  WHERE (\"host\" =~ /^$WLANPi$/) AND (\"smb_index\"=5)"
   }
  ]
 },
 "panels": [
  {
   "title": "Poll Status - $WLANPi",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "wiperf-poll-status",
     "query": "SELECT last(\"network\") AS \"Network\", last(\"ip\") AS \"IP Address\", last(\"speedtest\") AS \"Speedtest\", last(\"ping\") AS \"Ping Test\", last(\"dns\") AS \"DNS Test\", last(\"http\") AS \"HTTP Test\", last(\"iperf_tcp\") AS \"TCP iperf\", last(\"iperf_udp\") AS \"UDP iperf\", last(\"dhcp\") AS \"DHCP Test\", last(\"smb\") AS \"SMB Test\", last(\"auth\") AS \"Auth Test\", last(\"probe_mode\") AS \"Mode\", last(\"mgt_if\") AS \"Mgt I/F\", last(\"run_time\") AS \"Poll Cycle (s)\" FROM \"wiperf-poll-status\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "network" ], "type": "field" },
       { "params": [ "Network" ], "type": "alias" }
      ],
      [
       { "params": [ "ip" ], "type": "field" },
       { "params": [ "IP Address" ], "type": "alias" }
      ],
      [
       { "params": [ "speedtest" ], "type": "field" },
       { "params": [ "Speedtest" ], "type": "alias" }
      ],
      [
       { "params": [ "ping" ], "type": "field" },
       { "params": [ "Ping Test" ], "type": "alias" }
      ],
      [
       { "params": [ "dns" ], "type": "field" },
       { "params": [ "DNS Test" ], "type": "alias" }
      ],
      [
       { "params": [ "http" ], "type": "field" },
       { "params": [ "HTTP Test" ], "type": "alias" }
      ],
      [
       { "params": [ "iperf_tcp" ], "type": "field" },
       { "params": [ "TCP iperf" ], "type": "alias" }
      ],
      [
       { "params": [ "iperf_udp" ], "type": "field" },
       { "params": [ "UDP iperf" ], "type": "alias" }
      ],
      [
       { "params": [ "dhcp" ], "type": "field" },
       { "params": [ "DHCP Test" ], "type": "alias" }
      ],
      [
       { "params": [ "smb" ], "type": "field" },
       { "params": [ "SMB Test" ], "type": "alias" }
      ],
      [
       { "params": [ "probe_mode" ], "type": "field" },
       { "params": [ "Mode" ], "type": "alias" }
      ],
      [
       { "params": [ "mgt_if" ], "type": "field" },
       { "params": [ "Mgt I/F" ], "type": "alias" }
      ],
      [
       { "params": [ "run_time" ], "type": "field" },
       { "params": [ "Poll Cycle (s)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Connection Details - $WLANPi",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "wiperf-network",
     "query": "SELECT \"bssid\" AS \"BSSID\", \"ssid\" AS \"SSID\", \"channel\" AS \"Channel\", \"channel_width\" AS \"Width (MHz)\", \"tx_rate_mbps\" AS \"Tx Rate (Mbps)\", \"rx_rate_mbps\" AS \"Rx Rate (Mbps)\", \"signal_level_dbm\" AS \"RSSI (dBm)\" FROM \"wiperf-network\" WHERE (\"host\" =~ /^$WLANPi$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bssid" ], "type": "field" },
       { "params": [ "BSSID" ], "type": "alias" }
      ],
      [
       { "params": [ "ssid" ], "type": "field" },
       { "params": [ "SSID" ], "type": "alias" }
      ],
      [
       { "params": [ "channel" ], "type": "field" },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "channel_width" ], "type": "field" },
       { "params": [ "Width" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_rate_mbps" ], "type": "field" },
       { "params": [ "TX Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_rate_mbps" ], "type": "field" },
       { "params": [ "RX Rate (Mbps)" ], "type": "alias" }
      ],
      [
       { "params": [ "signal_level_dbm" ], "type": "field" },
       { "params": [ "RSSI (dBm)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  },
  {
   "title": "Poller Errors - $WLANPi",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "wiperf-poll-errors",
     "select": [
      [
       { "params": [ "error_message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$WLANPi$/" }
     ]
    }
   ]
  }
 ]
}